/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmailSignup = IDL.Record({
  'email' : IDL.Text,
  'signedUpAt' : IDL.Int,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const SubmitContactRequest = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '__emailSignups' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(EmailSignup)],
      ['query'],
    ),
  '__nextSubmissionId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__submissions' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'listContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'listEmailSignups' : IDL.Func([], [IDL.Vec(EmailSignup)], ['query']),
  'submitContactForm' : IDL.Func(
      [SubmitContactRequest],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'submitEmailSignup' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmailSignup = IDL.Record({
    'email' : IDL.Text,
    'signedUpAt' : IDL.Int,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const SubmitContactRequest = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '__emailSignups' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(EmailSignup)],
        ['query'],
      ),
    '__nextSubmissionId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__submissions' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'listContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'listEmailSignups' : IDL.Func([], [IDL.Vec(EmailSignup)], ['query']),
    'submitContactForm' : IDL.Func(
        [SubmitContactRequest],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'submitEmailSignup' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };